site_name: Cursos-Wine

theme:
  name: material
  palette:

    # Toggle light mode
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  
nav:
  - Home: index.md
  - Sobre: about.md
  - Criando o site: criando-o-site.md
  - Linux - introdução: linux-introducao.md
  - Linux - módulo 3: linux-modulo-3.md
  - Linux - módulo 4: linux-modulo-4.md
  - Docker - introdução: docker-introducao.md
  - Docker - módulo 1: docker-modulo-1.md
  - Docker - módulo 2: docker-modulo-2.md
  - Docker - módulo 3: docker-modulo-3.md
  - Docker - módulo 4: docker-modulo-4.md
  - Docker - módulo 5: docker-modulo-5.md
  - Docker - módulo 6: docker-modulo-6.md